_target_: ahcore.lit_module.AhCoreLightningModule

model:
  _target_: ahcore.models.attention_unet.AttentionUnet
  _partial_: true
  inp_channel: 3
  kernel_multiplier: 7
  depth: 4
  dropout_rate: 0.1
  return_features: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5e-4
  weight_decay: 1e-4
  betas:
    - 0.99
    - 0.9

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
