_target_: ahcore.lit_module.AhCoreLightningModule

model:
  _target_: ahcore.models.equivariant_unet.E2UNet
  _partial_: true
  group:
    _target_: escnn.gspaces.rot2dOnR2
    N: 8
  input_channels: 3
  num_layers: 3
  hidden_features: 32
  bilinear: true

#  dropout_prob: 0.1

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5e-4
  weight_decay: 1e-4
  betas:
    - 0.99
    - 0.9

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 100

