_target_: pytorch_lightning.Trainer

accelerator: cpu
devices: 1
max_epochs: 124
num_nodes: 1

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
log_every_n_steps: 2

# ckpt path
resume_from_checkpoint: null